library(shinythemes)

# Define UI for application that displays GEO results based on user choices
shinyUI(fluidPage(theme = shinytheme("cosmo"),
                  h1(strong("REALGAR"), align="center", style = "color: #9E443A;"),
                  h3(strong("Reducing Associations by Linking Genes And transcriptomic Results"), align="center", style = "color: #9E443A;"), hr(),
                  wellPanel(h4("Select options:",align = "left"), fluidRow(
                      column(2,checkboxGroupInput(inputId="Tissue", label="Tissue", choices=c("Bronchial epithelium"="BE",
                        "Nasal epithelium"="NE","CD4"="CD4","CD8"="CD8","PBMC"="PBMC","White blood cell"="WBC", "Airway smooth muscle"="ASM",
                        "BAL"="BAL", "Whole lung"="Lung"),selected="BE" )), 
                      column(2,checkboxGroupInput(inputId="Asthma", label="Condition", choices=c("Allergic asthma"="allergic_asthma",
                        "Severe asthma"="severe_asthma","Asthma"="asthma","Mild asthma"="mild_asthma","Non-allergic asthma"=
                        "non_allergic_asthma", "Asthma and rhinitis"="asthma_and_rhinitis", "Other"="NA"), selected="asthma"),
                        textInput(inputId="curr_gene",label="Type the official gene symbol:", value= "GAPDH")),
                        tags$head(tags$style(type="text/css", "#curr_gene {width: 190px}")),
                      column(6, p("Asthma Gene Explorer integrates publically available gene expression data from the", 
                        a("Gene Expression Omnibus (GEO),", href="http://www.ncbi.nlm.nih.gov/geo/"), 
                        " allowing researchers to easily access a breadth of information about tissue-specific gene expression", 
                        "related to asthma and glucocorticoid responsiveness.",
                        " The table below summarizes the datasets relevant to the conditions and tissue types selected,",
                        "with links to the original study and the full set of microarray expression data.",
                        " The plots aggregate data from these studies to display fold changes and p-values across all",
                        "relevant studies, as well as genome-wide association study (GWAS) data from ",
                        a("GRASP,", href="https://grasp.nhlbi.nih.gov/Search.aspx"), " for the gene of interest. ",
                        "Note that fold changes were computed with a reference patten of asthma vs. [other type of asthma]."), br()), 
                      column(6, fluidRow(img(src="http://shiny.rstudio.com/tutorial/lesson2/www/bigorb.png", height=42, width=48),
                                         "Created with RStudio's ",
                                         a("Shiny", href="http://www.rstudio.com/shiny"))))),
                    mainPanel(h4(strong("Datasets loaded:"), align="left"),
                      fluidRow(align="left",column(12, DT::dataTableOutput(outputId="GEO_table"))),
                      fluidRow(align="left", br(), br(),
                               column(6,plotOutput(outputId="fc_plot",width="95%", height="650px")),
                               column(6,plotOutput(outputId="pval_plot",width="95%", height="650px")), br(), br()),
                      h4(strong("Data displayed in plots above:"), align="left"),
                      fluidRow(align="center", br(), column(12, DT::dataTableOutput(outputId="tableforgraph"))),
                      fixedRow(align="center",br(),
                               downloadButton(outputId="fc_download",label="Download Fold Change Plot"),
                               downloadButton(outputId="pval_download", label="Download P-Value Plot"),
                               downloadButton(outputId="table_download", label="Download heatmap data")),br())))
